Facilitator communication
Equideum/FedML pull request #1
Opened 2021-12-10 10:55 UTC by annabeer

This is the communication with the help of a facilitator and represents a different form of vertical federated learning

2022-01-25 11:35 UTC, jopasserat requested changes
- minor fixes on how the files are organised
- we might want to remove some superfluous classes (but aren't they all? ^^)
- we'll need more doc, especially docstrings at the top of functions/classes to describing their purpose
  - a `README.md` in the folder introducing what this demo does, who are the actors, ... would be great (prime location for the diagram we have [here](https://lucid.app/lucidchart/ac9bc857-3c14-46e5-bb96-1d6337cfdc0d/edit?invitationId=inv_d1e70c1f-7030-462d-b8f6-02c2f58f13da&page=0_0#) if we manage to reconcile the naming between diagram and code
- before switching to the new dataset, need to understand how to move from this simulation mode to the distributed version 
  - see this https://github.com/FedML-AI/FedML/blob/master/fedml_experiments/distributed/classical_vertical_fl/main_vfl.py
  - and this https://github.com/FedML-AI/FedML/blob/master/fedml_experiments/distributed/split_nn/main_split_nn.py

2022-01-25 13:13 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/vfl_fixture_fascilitator.py
> +class FederatedLearningFixture(object):
This was in line with vfl_fixture set up. Let me know how to adjust it :)

2022-01-25 13:16 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/vfl_fixture_fascilitator.py
> +        print("Step 7: initialize FederatedLearningFixture")
This was in line with vfl_fixture set up. Let me know how to adjust it :)

2022-01-25 13:17 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/vfl_fixture_fascilitator.py
> +                for party_id, party_X in train_data["party_list"].items():
That makes two of us

2022-01-25 13:20 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/vfl_fascilitator.py
> +        if self.is_debug: print("==> Guest computes loss")
Neither did I until I looked at their code!

2022-01-25 16:23 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/party_models_fascilitator.py
> +def sigmoid(x):
As in _compute_loss(self, y)?

2022-01-25 16:37 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/party_models_fascilitator.py
> +class VFLGuestModel(object):
Made changes to the files. We can discuss later if this is sufficient :)

2022-01-25 16:38 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/party_models_fascilitator.py
> +        if self.is_debug: print("Step 1: Set batch for Host")
True. Just kept the same format as the other example. Let me know if you want me to change it!

2022-01-25 16:39 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/vfl_fascilitator.py
> +class VerticalMultiplePartyLogisticRegressionFederatedLearning(object):
Yes :)

2022-01-25 16:41 UTC, annabeer commented on fedml_experiments/standalone/classical_vertical_fl/run_vfl_fc_two_party_lending_club_facilitator.py
> +    federatedLearning = VerticalMultiplePartyLogisticRegressionFederatedLearning(partyA)
Sorry this was a mistake while pushing it...

2022-01-25 17:09 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/vfl_fascilitator.py
> +    def fit(self, y, party_X_dict, global_step):
Can we please clarify this in the call?

2022-01-25 18:06 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/party_models_fascilitator.py
> +def sigmoid(x):
No this one /Users/Anna/Desktop/FedML_New/FedML/fedml_api/standalone/classical_vertical_fl/vfl_fixture_fascilitator.py

2022-01-25 18:19 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/vfl_fascilitator.py
> +    def fit(self, y, party_X_dict, global_step):
(x: int, X_train: np.array[float])

2022-01-25 18:22 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/vfl_fascilitator.py
> +    def fit(self, y, party_X_dict, global_step):
def _create_dataset_with_mapping(
    image_dir: str, mapping: List[Dict[str, str]]) -> List[tf.train.Example]:

2022-02-14 20:33 UTC, jopasserat reviewed
getting there! :)

2022-02-14 20:33 UTC, jopasserat commented on fedml_api/standalone/classical_vertical_fl/party_models_fascilitator.py
> +            logger.info("Step 5:receives the activation")
would opt for `logger.debug` for all such debug prints

2022-02-14 20:33 UTC, jopasserat commented on README_facilitator.md
> +
make it clear that it's simulated FL for now, even if folder structure hints at it

2022-02-14 20:33 UTC, jopasserat commented on fedml_api/standalone/classical_vertical_fl/vfl_fixture_fascilitator.py
> +class FederatedLearningFixture(object):
this one is easier to "de-objectify" than the others -> you're never using the object's internal state (`self.XXX`) to store / retrieve any thing from one call to another.
the only field is this "god object" federated learning which could just be passed as input param to the fit method

2022-02-14 20:33 UTC, jopasserat commented on fedml_api/standalone/classical_vertical_fl/vfl_fixture_fascilitator.py
> +class FederatedLearningFixture(object):
meaning in turn that `fit()` can become a function since it's the only thing in the whole class and not accessing any internal state anymore

2022-02-15 09:53 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/party_models_fascilitator.py
> +            self.final_act = self._fit(final_act)
So the if and else statement in the _fit() or what does this mean?

2022-02-15 10:59 UTC, jopasserat commented on fedml_api/standalone/classical_vertical_fl/party_models_fascilitator.py
> +            self.final_act = self._fit(final_act)
yeah these 2 blocks of 4 lines are the same, so you can group them in a function with a meaningful name, and call it in both places

2022-02-15 13:40 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/party_models_fascilitator.py
> +        grads = torch.autograd.grad(outputs=class_loss, inputs=U)
class_loss.grad would return none since we havent called backward

2022-02-15 13:42 UTC, annabeer commented on fedml_api/standalone/classical_vertical_fl/party_models_fascilitator.py
> +        self.top_grads = grads[0].numpy()
to access the grads its of form (tensor([[...],...,[...]]),) This is done in the same manner as FedML

2022-02-18 16:59 UTC, jopasserat approved these changes
Super minor final change over a function vs method :pray: 

Fantastic work on improving this PR :1st_place_medal:

2022-02-18 16:59 UTC, jopasserat commented on fedml_api/standalone/classical_vertical_fl/party_models_facilitator.py
> +        Returns: the final activations
doesn't seem like you're returning anything here :)
small design tip: when you're writing this kind of short functions to be reused in various places of the codebase, avoid modifying the internal state and favour returning the new value instead. you can then do the assignment to the internal state if you want/need to when calling the generic function

2022-02-18 16:59 UTC, jopasserat commented on fedml_api/standalone/classical_vertical_fl/party_models_facilitator.py
> +        Returns: the final activations
in general, avoid modifying internal states whenever as much as possible, it makes your code harder to reuse ;)

2022-02-18 16:59 UTC, jopasserat commented on fedml_api/standalone/classical_vertical_fl/party_models_facilitator.py
> +        Returns: the final activations
just like you did for `fed_learning_fixture_fit` actually :+1:

2022-02-21 10:19 UTC, merged